[project]
name = "mcpy"
version = "0.1.0"
description = "A python package to run atomistic Monte Carlo simulations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ase>=3.23.0",
    "mace-torch>=0.3.9",
]
